call pathogen#infect()

syntax enable
set nocompatible
filetype plugin indent on
set title
set history=1000
set wildmenu "shows options for command completion with <TAB>
set wildmode=list:longest

set ignorecase 
set smartcase

colorscheme molokai

set showcmd

" Setup closetag plugin for html/xml like files
autocmd FileType html,htmldjango,jinjahtml,eruby,mako let b:closetag_html_style=1 
autocmd FileType html,xhtml,xml,htmldjango,jinjahtml,eruby,mako source ~/.vim/bundle/closetag/plugin/closetag.vim
