call pathogen#infect()
syntax enable
"Setup solarized colorscheme"
if has('gui_running')
    set background=dark
else
    set background=dark
endif
set t_Co=256
let g:solarized_termcolors=16
colorscheme solarized
syntax enable
set nocompatible
filetype plugin indent on
set title
set history=1000
set wildmenu "shows options for command completion with <TAB>
set wildmode=list:longest
set guioptions-=T "removes toolbar
set ignorecase 
set smartcase
set showcmd
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab
set expandtab
"set rnu "sets relative line numbering set nu to get line numbering

" Setup closetag plugin for html/xml like files
autocmd FileType html,htmldjango,jinjahtml,eruby,mako let b:closetag_html_style=1 
autocmd FileType html,xhtml,xml,htmldjango,jinjahtml,eruby,mako source ~/.vim/bundle/closetag/plugin/closetag.vim
